---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# eavtools

The goal of eavtools is to provide shims to dplyr functions to work with data in Entity-Attribute-Value format *as if* it were tidy.

## Installation

You can (cannot) install the released version of eavtools from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("eavtools")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
## basic example code
library(tidyverse)
library(eavtools)

tinyeav <- tiny %>%
	new_tbl_eav("empid", "var", "value")

tinyeav
```

```{r}
str(tinyeav)
```

```{r}
tiny %>%
	dplyr::group_by(empid) %>%
	dplyr::summarize(
		first  = value %forwhich% (var == "first"),
		middle = value %forwhich% (var == "middle"),
		last   = value %forwhich% (var == "last")
	)
```

